# Generated by Django 4.2.10 on 2024-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=266, null=True)),
                ('category', models.CharField(blank=True, max_length=266, null=True)),
                ('mode', models.CharField(blank=True, default='Yard', max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=266, null=True)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('original_pics', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pics1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pics2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pics3', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
