# Generated by Django 4.2.10 on 2024-02-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide1heading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide1subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide1writeup', models.CharField(blank=True, max_length=250, null=True)),
                ('slide2pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide2heading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide2subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide2writeup', models.CharField(blank=True, max_length=250, null=True)),
                ('slide3pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide3heading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide3subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide3writeup', models.CharField(blank=True, max_length=250, null=True)),
                ('slide4pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide4heading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide4subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide4writeup', models.CharField(blank=True, max_length=250, null=True)),
                ('slide5pics', models.ImageField(blank=True, null=True, upload_to='')),
                ('slide5heading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide5subheading', models.CharField(blank=True, max_length=250, null=True)),
                ('slide5writeup', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
